#DB configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.100.209:3306/microservice
    username: root
    password: fkS#jkD2@La

#loggind
logging:
  level:
    com.yangguojun.web: debug